/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpendingsRouteImport } from './routes/spendings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsSpendingsRouteImport } from './routes/reports/spendings'
import { Route as ReportsSpendingValueRangeRouteImport } from './routes/reports/spending-value-range'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ApiSpendingsIndexRouteImport } from './routes/api/spendings/index'
import { Route as ApiEmployeesIndexRouteImport } from './routes/api/employees/index'
import { Route as ApiDepartmentsIndexRouteImport } from './routes/api/departments/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiSpendingsSpendingIdRouteImport } from './routes/api/spendings/$spendingId'
import { Route as ApiReportsSpendingsRouteImport } from './routes/api/reports/spendings'
import { Route as ApiReportsSpendingValueRangeRouteImport } from './routes/api/reports/spending-value-range'
import { Route as ApiEmployeesEmployeeIdRouteImport } from './routes/api/employees/$employeeId'
import { Route as ApiDepartmentsDepartmentIdRouteImport } from './routes/api/departments/$departmentId'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiReportsSpendingValueRangeXlsxRouteImport } from './routes/api/reports/spending-value-range.xlsx'
import { Route as ApiReportsSpendingValueRangePdfRouteImport } from './routes/api/reports/spending-value-range.pdf'

const SpendingsRoute = SpendingsRouteImport.update({
  id: '/spendings',
  path: '/spendings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSpendingsRoute = ReportsSpendingsRouteImport.update({
  id: '/reports/spendings',
  path: '/reports/spendings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSpendingValueRangeRoute =
  ReportsSpendingValueRangeRouteImport.update({
    id: '/reports/spending-value-range',
    path: '/reports/spending-value-range',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpendingsIndexRoute = ApiSpendingsIndexRouteImport.update({
  id: '/api/spendings/',
  path: '/api/spendings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesIndexRoute = ApiEmployeesIndexRouteImport.update({
  id: '/api/employees/',
  path: '/api/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentsIndexRoute = ApiDepartmentsIndexRouteImport.update({
  id: '/api/departments/',
  path: '/api/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpendingsSpendingIdRoute = ApiSpendingsSpendingIdRouteImport.update({
  id: '/api/spendings/$spendingId',
  path: '/api/spendings/$spendingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsSpendingsRoute = ApiReportsSpendingsRouteImport.update({
  id: '/api/reports/spendings',
  path: '/api/reports/spendings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsSpendingValueRangeRoute =
  ApiReportsSpendingValueRangeRouteImport.update({
    id: '/api/reports/spending-value-range',
    path: '/api/reports/spending-value-range',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmployeesEmployeeIdRoute = ApiEmployeesEmployeeIdRouteImport.update({
  id: '/api/employees/$employeeId',
  path: '/api/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentsDepartmentIdRoute =
  ApiDepartmentsDepartmentIdRouteImport.update({
    id: '/api/departments/$departmentId',
    path: '/api/departments/$departmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsSpendingValueRangeXlsxRoute =
  ApiReportsSpendingValueRangeXlsxRouteImport.update({
    id: '/xlsx',
    path: '/xlsx',
    getParentRoute: () => ApiReportsSpendingValueRangeRoute,
  } as any)
const ApiReportsSpendingValueRangePdfRoute =
  ApiReportsSpendingValueRangePdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => ApiReportsSpendingValueRangeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/spendings': typeof SpendingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/reports/spending-value-range': typeof ReportsSpendingValueRangeRoute
  '/reports/spendings': typeof ReportsSpendingsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/departments/$departmentId': typeof ApiDepartmentsDepartmentIdRoute
  '/api/employees/$employeeId': typeof ApiEmployeesEmployeeIdRoute
  '/api/reports/spending-value-range': typeof ApiReportsSpendingValueRangeRouteWithChildren
  '/api/reports/spendings': typeof ApiReportsSpendingsRoute
  '/api/spendings/$spendingId': typeof ApiSpendingsSpendingIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/api/departments/': typeof ApiDepartmentsIndexRoute
  '/api/employees/': typeof ApiEmployeesIndexRoute
  '/api/spendings/': typeof ApiSpendingsIndexRoute
  '/api/reports/spending-value-range/pdf': typeof ApiReportsSpendingValueRangePdfRoute
  '/api/reports/spending-value-range/xlsx': typeof ApiReportsSpendingValueRangeXlsxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/spendings': typeof SpendingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/reports/spending-value-range': typeof ReportsSpendingValueRangeRoute
  '/reports/spendings': typeof ReportsSpendingsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/departments/$departmentId': typeof ApiDepartmentsDepartmentIdRoute
  '/api/employees/$employeeId': typeof ApiEmployeesEmployeeIdRoute
  '/api/reports/spending-value-range': typeof ApiReportsSpendingValueRangeRouteWithChildren
  '/api/reports/spendings': typeof ApiReportsSpendingsRoute
  '/api/spendings/$spendingId': typeof ApiSpendingsSpendingIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/api/departments': typeof ApiDepartmentsIndexRoute
  '/api/employees': typeof ApiEmployeesIndexRoute
  '/api/spendings': typeof ApiSpendingsIndexRoute
  '/api/reports/spending-value-range/pdf': typeof ApiReportsSpendingValueRangePdfRoute
  '/api/reports/spending-value-range/xlsx': typeof ApiReportsSpendingValueRangeXlsxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/spendings': typeof SpendingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/reports/spending-value-range': typeof ReportsSpendingValueRangeRoute
  '/reports/spendings': typeof ReportsSpendingsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/departments/$departmentId': typeof ApiDepartmentsDepartmentIdRoute
  '/api/employees/$employeeId': typeof ApiEmployeesEmployeeIdRoute
  '/api/reports/spending-value-range': typeof ApiReportsSpendingValueRangeRouteWithChildren
  '/api/reports/spendings': typeof ApiReportsSpendingsRoute
  '/api/spendings/$spendingId': typeof ApiSpendingsSpendingIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/api/departments/': typeof ApiDepartmentsIndexRoute
  '/api/employees/': typeof ApiEmployeesIndexRoute
  '/api/spendings/': typeof ApiSpendingsIndexRoute
  '/api/reports/spending-value-range/pdf': typeof ApiReportsSpendingValueRangePdfRoute
  '/api/reports/spending-value-range/xlsx': typeof ApiReportsSpendingValueRangeXlsxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/departments'
    | '/employees'
    | '/login'
    | '/spendings'
    | '/demo/tanstack-query'
    | '/reports/spending-value-range'
    | '/reports/spendings'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/departments/$departmentId'
    | '/api/employees/$employeeId'
    | '/api/reports/spending-value-range'
    | '/api/reports/spendings'
    | '/api/spendings/$spendingId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/api/departments/'
    | '/api/employees/'
    | '/api/spendings/'
    | '/api/reports/spending-value-range/pdf'
    | '/api/reports/spending-value-range/xlsx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/departments'
    | '/employees'
    | '/login'
    | '/spendings'
    | '/demo/tanstack-query'
    | '/reports/spending-value-range'
    | '/reports/spendings'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/departments/$departmentId'
    | '/api/employees/$employeeId'
    | '/api/reports/spending-value-range'
    | '/api/reports/spendings'
    | '/api/spendings/$spendingId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/api/departments'
    | '/api/employees'
    | '/api/spendings'
    | '/api/reports/spending-value-range/pdf'
    | '/api/reports/spending-value-range/xlsx'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/departments'
    | '/employees'
    | '/login'
    | '/spendings'
    | '/demo/tanstack-query'
    | '/reports/spending-value-range'
    | '/reports/spendings'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/departments/$departmentId'
    | '/api/employees/$employeeId'
    | '/api/reports/spending-value-range'
    | '/api/reports/spendings'
    | '/api/spendings/$spendingId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/api/departments/'
    | '/api/employees/'
    | '/api/spendings/'
    | '/api/reports/spending-value-range/pdf'
    | '/api/reports/spending-value-range/xlsx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EmployeesRoute: typeof EmployeesRoute
  LoginRoute: typeof LoginRoute
  SpendingsRoute: typeof SpendingsRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ReportsSpendingValueRangeRoute: typeof ReportsSpendingValueRangeRoute
  ReportsSpendingsRoute: typeof ReportsSpendingsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiDepartmentsDepartmentIdRoute: typeof ApiDepartmentsDepartmentIdRoute
  ApiEmployeesEmployeeIdRoute: typeof ApiEmployeesEmployeeIdRoute
  ApiReportsSpendingValueRangeRoute: typeof ApiReportsSpendingValueRangeRouteWithChildren
  ApiReportsSpendingsRoute: typeof ApiReportsSpendingsRoute
  ApiSpendingsSpendingIdRoute: typeof ApiSpendingsSpendingIdRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  ApiDepartmentsIndexRoute: typeof ApiDepartmentsIndexRoute
  ApiEmployeesIndexRoute: typeof ApiEmployeesIndexRoute
  ApiSpendingsIndexRoute: typeof ApiSpendingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spendings': {
      id: '/spendings'
      path: '/spendings'
      fullPath: '/spendings'
      preLoaderRoute: typeof SpendingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/spendings': {
      id: '/reports/spendings'
      path: '/reports/spendings'
      fullPath: '/reports/spendings'
      preLoaderRoute: typeof ReportsSpendingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/spending-value-range': {
      id: '/reports/spending-value-range'
      path: '/reports/spending-value-range'
      fullPath: '/reports/spending-value-range'
      preLoaderRoute: typeof ReportsSpendingValueRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spendings/': {
      id: '/api/spendings/'
      path: '/api/spendings'
      fullPath: '/api/spendings/'
      preLoaderRoute: typeof ApiSpendingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/': {
      id: '/api/employees/'
      path: '/api/employees'
      fullPath: '/api/employees/'
      preLoaderRoute: typeof ApiEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departments/': {
      id: '/api/departments/'
      path: '/api/departments'
      fullPath: '/api/departments/'
      preLoaderRoute: typeof ApiDepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spendings/$spendingId': {
      id: '/api/spendings/$spendingId'
      path: '/api/spendings/$spendingId'
      fullPath: '/api/spendings/$spendingId'
      preLoaderRoute: typeof ApiSpendingsSpendingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/spendings': {
      id: '/api/reports/spendings'
      path: '/api/reports/spendings'
      fullPath: '/api/reports/spendings'
      preLoaderRoute: typeof ApiReportsSpendingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/spending-value-range': {
      id: '/api/reports/spending-value-range'
      path: '/api/reports/spending-value-range'
      fullPath: '/api/reports/spending-value-range'
      preLoaderRoute: typeof ApiReportsSpendingValueRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/$employeeId': {
      id: '/api/employees/$employeeId'
      path: '/api/employees/$employeeId'
      fullPath: '/api/employees/$employeeId'
      preLoaderRoute: typeof ApiEmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departments/$departmentId': {
      id: '/api/departments/$departmentId'
      path: '/api/departments/$departmentId'
      fullPath: '/api/departments/$departmentId'
      preLoaderRoute: typeof ApiDepartmentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/spending-value-range/xlsx': {
      id: '/api/reports/spending-value-range/xlsx'
      path: '/xlsx'
      fullPath: '/api/reports/spending-value-range/xlsx'
      preLoaderRoute: typeof ApiReportsSpendingValueRangeXlsxRouteImport
      parentRoute: typeof ApiReportsSpendingValueRangeRoute
    }
    '/api/reports/spending-value-range/pdf': {
      id: '/api/reports/spending-value-range/pdf'
      path: '/pdf'
      fullPath: '/api/reports/spending-value-range/pdf'
      preLoaderRoute: typeof ApiReportsSpendingValueRangePdfRouteImport
      parentRoute: typeof ApiReportsSpendingValueRangeRoute
    }
  }
}

interface ApiReportsSpendingValueRangeRouteChildren {
  ApiReportsSpendingValueRangePdfRoute: typeof ApiReportsSpendingValueRangePdfRoute
  ApiReportsSpendingValueRangeXlsxRoute: typeof ApiReportsSpendingValueRangeXlsxRoute
}

const ApiReportsSpendingValueRangeRouteChildren: ApiReportsSpendingValueRangeRouteChildren =
  {
    ApiReportsSpendingValueRangePdfRoute: ApiReportsSpendingValueRangePdfRoute,
    ApiReportsSpendingValueRangeXlsxRoute:
      ApiReportsSpendingValueRangeXlsxRoute,
  }

const ApiReportsSpendingValueRangeRouteWithChildren =
  ApiReportsSpendingValueRangeRoute._addFileChildren(
    ApiReportsSpendingValueRangeRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DepartmentsRoute: DepartmentsRoute,
  EmployeesRoute: EmployeesRoute,
  LoginRoute: LoginRoute,
  SpendingsRoute: SpendingsRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ReportsSpendingValueRangeRoute: ReportsSpendingValueRangeRoute,
  ReportsSpendingsRoute: ReportsSpendingsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiDepartmentsDepartmentIdRoute: ApiDepartmentsDepartmentIdRoute,
  ApiEmployeesEmployeeIdRoute: ApiEmployeesEmployeeIdRoute,
  ApiReportsSpendingValueRangeRoute:
    ApiReportsSpendingValueRangeRouteWithChildren,
  ApiReportsSpendingsRoute: ApiReportsSpendingsRoute,
  ApiSpendingsSpendingIdRoute: ApiSpendingsSpendingIdRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  ApiDepartmentsIndexRoute: ApiDepartmentsIndexRoute,
  ApiEmployeesIndexRoute: ApiEmployeesIndexRoute,
  ApiSpendingsIndexRoute: ApiSpendingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
